### ISSUE TITLE
[help] i can't see bans status

### ISSUE THREAD

**Issue by Drmohammad11** [ge-ku/Ban-Checker-for-Steam#33]
hi
i have this error:
Error while scanning players for bans:
SyntaxError: Unexpected end of JSON input

Couldn't scan for bans after 3 retries :(

**Comment by Alexandr987** [comment]
Same, need fix

**Comment by ge-ku** [comment]
Hello, this is due to new requirement for extensions, [ericek111 fixed it for recently played / friends portion](https://github.com/ge-ku/Ban-Checker-for-Steam/pull/32) and explained it with links (this is not yet uploaded to Chrome store), I'll try to fix it for CS:GO history a bit later (probably on a weekend).

**Comment by ge-ku** [comment]
Never mind, ericek111 made it very reusable, should work now with CS:GO match history (version 1.2.3.1, now in Chrome store).
