### ISSUE TITLE
Ban Checker does not work in Firefox Quantum 57.0

### ISSUE THREAD

**Issue by xitero** [ge-ku/Ban-Checker-for-Steam#8]
In Google Chrome, when I click the Ban Checker tab, it shows the list of users banned normally, but in Firefox, the following appears: https://i.imgur.com/xX2ZOPZ.png

I already tried using a custom API key, but it also did not work.
When I click on "Load 15 more games" or "Load all games", nothing happens.

**Comment by ge-ku** [comment]
Hello, thanks for letting me know! I found [where the issue is](https://github.com/ge-ku/Ban-Checker-for-Steam/commit/1a129ab78b6506c62d2ede3eed8071a6b84e22b8) and uploaded new version (1.0.10) for Chrome and Firefox. I'm pretty sure it was affecting Chrome too but only for fresh installs of extension.

**Comment by xitero** [comment]
I updated my Firefox extension but I still have the same problem. I even tried to reinstall it, it did not work.

**Comment by xitero** [comment]
My mistake, works fine, thanks for the update!
